version: 1
formatters:
  common:
    format: "%(asctime)s.%(msecs)03d - %(levelname)s - %(threadName)s - %(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S"
  console:
    format: "%(asctime)s.%(msecs)03d - %(levelname)s - %(pathname)s - %(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S"
handlers:
  common:
    class: logging.handlers.TimedRotatingFileHandler
    formatter: common
    when: D
    interval: 1
    encoding: utf8
    filename: "running.log"
    backupCount: 15
  console:
    class : logging.StreamHandler
    formatter: console
    stream  : ext://sys.stdout
loggers:
  main.common:
    level: INFO
    handlers: [common]
root:
  level: DEBUG
  handlers: [console]